# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from request import LookupRequest_pb2 as request_dot_LookupRequest__pb2
from request import TradeRequest_pb2 as request_dot_TradeRequest__pb2
from request import UpdateRequest_pb2 as request_dot_UpdateRequest__pb2
from response import LookUpResponse_pb2 as response_dot_LookUpResponse__pb2
from response import TradeResponse_pb2 as response_dot_TradeResponse__pb2
from response import UpdateResponse_pb2 as response_dot_UpdateResponse__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service/StockTradingService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockTradingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/StockTrading/Lookup',
                request_serializer=request_dot_LookupRequest__pb2.LookupRequest.SerializeToString,
                response_deserializer=response_dot_LookUpResponse__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.Trade = channel.unary_unary(
                '/StockTrading/Trade',
                request_serializer=request_dot_TradeRequest__pb2.TradeRequest.SerializeToString,
                response_deserializer=response_dot_TradeResponse__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/StockTrading/Update',
                request_serializer=request_dot_UpdateRequest__pb2.UpdateRequest.SerializeToString,
                response_deserializer=response_dot_UpdateResponse__pb2.UpdateResponse.FromString,
                _registered_method=True)


class StockTradingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockTradingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=request_dot_LookupRequest__pb2.LookupRequest.FromString,
                    response_serializer=response_dot_LookUpResponse__pb2.LookupResponse.SerializeToString,
            ),
            'Trade': grpc.unary_unary_rpc_method_handler(
                    servicer.Trade,
                    request_deserializer=request_dot_TradeRequest__pb2.TradeRequest.FromString,
                    response_serializer=response_dot_TradeResponse__pb2.TradeResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=request_dot_UpdateRequest__pb2.UpdateRequest.FromString,
                    response_serializer=response_dot_UpdateResponse__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StockTrading', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StockTrading', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockTrading(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StockTrading/Lookup',
            request_dot_LookupRequest__pb2.LookupRequest.SerializeToString,
            response_dot_LookUpResponse__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StockTrading/Trade',
            request_dot_TradeRequest__pb2.TradeRequest.SerializeToString,
            response_dot_TradeResponse__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StockTrading/Update',
            request_dot_UpdateRequest__pb2.UpdateRequest.SerializeToString,
            response_dot_UpdateResponse__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
