# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/StockTradingService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service/StockTradingService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from request import LookupRequest_pb2 as request_dot_LookupRequest__pb2
from request import TradeRequest_pb2 as request_dot_TradeRequest__pb2
from request import UpdateRequest_pb2 as request_dot_UpdateRequest__pb2
from response import LookUpResponse_pb2 as response_dot_LookUpResponse__pb2
from response import TradeResponse_pb2 as response_dot_TradeResponse__pb2
from response import UpdateResponse_pb2 as response_dot_UpdateResponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!service/StockTradingService.proto\x1a\x1brequest/LookupRequest.proto\x1a\x1arequest/TradeRequest.proto\x1a\x1brequest/UpdateRequest.proto\x1a\x1dresponse/LookUpResponse.proto\x1a\x1cresponse/TradeResponse.proto\x1a\x1dresponse/UpdateResponse.proto2\x92\x01\n\x0cStockTrading\x12+\n\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\"\x00\x12(\n\x05Trade\x12\r.TradeRequest\x1a\x0e.TradeResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.StockTradingService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKTRADING']._serialized_start=216
  _globals['_STOCKTRADING']._serialized_end=362
# @@protoc_insertion_point(module_scope)
