# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StockTrading.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'StockTrading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12StockTrading.proto\"\"\n\rLookupRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\"A\n\x0cTradeRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x10\n\x08itemSize\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\"1\n\rUpdateRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"/\n\x0eLookupResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0e\n\x06volume\x18\x02 \x01(\x03\"\"\n\rTradeResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x03\"#\n\x0eUpdateResponse\x12\x11\n\tisUpdated\x18\x01 \x01(\x03\x32\x92\x01\n\x0cStockTrading\x12+\n\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\"\x00\x12(\n\x05Trade\x12\r.TradeRequest\x1a\x0e.TradeResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StockTrading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=22
  _globals['_LOOKUPREQUEST']._serialized_end=56
  _globals['_TRADEREQUEST']._serialized_start=58
  _globals['_TRADEREQUEST']._serialized_end=123
  _globals['_UPDATEREQUEST']._serialized_start=125
  _globals['_UPDATEREQUEST']._serialized_end=174
  _globals['_LOOKUPRESPONSE']._serialized_start=176
  _globals['_LOOKUPRESPONSE']._serialized_end=223
  _globals['_TRADERESPONSE']._serialized_start=225
  _globals['_TRADERESPONSE']._serialized_end=259
  _globals['_UPDATERESPONSE']._serialized_start=261
  _globals['_UPDATERESPONSE']._serialized_end=296
  _globals['_STOCKTRADING']._serialized_start=299
  _globals['_STOCKTRADING']._serialized_end=445
# @@protoc_insertion_point(module_scope)
